### ISSUE TITLE
labsplit - case is missing if strlen shorter than wrap

### ISSUE THREAD

**Issue by mkaulisch** [asjadnaqvi/stata-graphfunctions#2]
Dear Asjad,
I found that -labsplit- makes strings missing if the length of wrap is longer than the length of the string.
See:

```
frame create auto
cwf auto
sysuse auto
labsplit make, gen(make_s) wrap(10)
tab make_s
```

make has 74 cases but make_s has only 54...

**Comment by asjadnaqvi** [comment]
Fixed in v1.2

```stata
sysuse auto, clear

keep price weight make
labsplit make, gen(make2) wrap(10)

scatter price weight, mlabel(make)
scatter price weight, mlabel(make2)
```


![bugfix1](https://github.com/user-attachments/assets/fd3aeed7-a857-4314-a844-f78e9af87baf)
![bugfix2](https://github.com/user-attachments/assets/4163d674-d2a6-4585-b72c-c1acadac7e54)
